### ISSUE TITLE
.DS_Store shouldn't be checked in

### ISSUE THREAD

**Issue by brlin-tw** [ckanthony/Popcat-Click-Bot#1]
Just want to leave a note after unintentionally surf past [your Reddit post](https://www.reddit.com/r/PopCat/comments/p3jdcy/just_wrote_a_bot_to_meow_9999_times_so_i_dont/), cheers!

**Comment by ckanthony** [comment]
@Lin-Buo-Ren nice catch!  Thanks for your pass by!  If you enjoy my work, don't forget to give me a star 🙇🏻‍♂️ 😄

**Comment by brlin-tw** [comment]
Sure thing!
